spring:
  application:
    name: hub
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: PlatformHubHikariCP
      minimum-idle: 10
      maximum-pool-size: 50
      max-lifetime: 600000
      idle-timeout: 300000
      auto-commit: true

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  file:
    path: "logs/"

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types:
      - application/json
      - text/html
      - text/plain
