spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/hubdb
    username: hub
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  file:
    prefix: PROD